### ISSUE TITLE
shared values and consensus

### ISSUE THREAD

**Issue by mnot** [w3c/AB-public#129]
> The goal of this document is to [...] be grounded enough in the shared values of the W3C community to represent the emergent consensus of most of our participants.

That phrasing is odd; consensus is a [well-defined term](https://www.w3.org/2023/Process-20230612/#Consensus) in the W3C, and it isn't acheived based upon what it's 'grounded' in. Also, 'most' is redundant.

I'd suggest something like:

> The goal of this document is to [...] reflect W3C consensus regarding the shared values of the community.

**Comment by TzviyaSiegman** [comment]
I believe this is corrected in current draft. OK to close @mnot ?

**Comment by mnot** [comment]
I don't see any change in the current ED.

**Comment by fantasai** [comment]
Agree that the quoted text is still what's in the draft, but disagree that we should change the sentence. I quite like the way it's phrased.

Yes, W3C has a technical definition for consensus that we use in the process, but this sentence is using consensus in a more generic way, as evidenced in the phrasing "emergent consensus of _most of our participants_". That phrasing is very intentional.

The goal of this document is (explicitly) not to reflect the consensus of all W3C Members. We have a very wide Membership, with many differing opinions, and a document that every member can agree with is not likely to be a document that has much meaningful guidance. The Vision needs to provide meaningful guidance, and it therefore needs to be a document with which people might disagree.

But we can create a document that _most_ of our participants can agree articulates our values as an organization. And that is our goal: to articulate the values that this organization already has. They might not be values that are _universally_ held,  but they should be values that are widely and deeply held in our community. And I think the existing sentence does an accurate job of articulating this goal.

Therefore, +1 to close, explicitly with no change.

**Comment by chaals** [comment]
The technical definition we use of consensus is specifically intended to deal with the fact that not everyone might actually agree, but everyone can live with something.

If the AB doesn't aim to reach that level, I'm actually really concerned about them aiming to publish a Note. 

Essentially, I'd like to understand which members' opinions don't count and can be ignored in the discussion - is it based on specific opinions, or specific types of member, or specific participants, or what? Or is it actually the case that the AB is aiming for what e generally define as consensus, in which case I think this issue and @mnot's proposed phrasing make a lot of sense.

**Comment by frivoal** [comment]
The Process has a definition of concensus, but decisions can happen even in the absence of consensus. A formal objection means there's no consensus, but it doesn't mean the work is dead and we cannot move forward. Sometimes we decide to side with the FO, and require a rework, but sometimes we decide to overrule the FO and publish anyway. That's still not consensus, but that's a decision, and this is something we accept for charters, RECS, etc.

Getting formal objections is not a goal obviously, so there is no deliberate intent to move forward with 5% of the membership opposing, or with 7 specific people that we don't like opposing.

But I think it is wise to recognize that an opinionated document that identifies deeply held values that an overwhelming majority agrees with will still likely have some detractors, and thus not have consensus. I think it is a reasonable objective to try to aim for identify the core of what makes this community tick, rather than trying to identify platitudes that are generic enough that nobody could possibly disagree.

I'd imagine that when we get to an AC review, if we have chosen to reject some strongly held opinions, we ought to have a strong documented rationale for that, and submit that along with the Document.

For instance, if we go to AC review with: "Here's what we wrote, some people don't like it, deal with it", that would not be acceptable, and the AC ought to reject it (even those who actually like the text).

On the other hand, if we go with this: "Here's what we wrote. We chose to reject the view, held by a few people, that accessibility was merely nice to have but not all that important and thus didn't need mentioning, because we think this doesn't reflect the deeply and broadly held views of this community. See XYZ for details of that conversation." Then I think we'd have done a the right thing.

So, it would be preferable to have consensus in the Process sense, but it's not the goal. As such, the sentence as it currently is is fine by me, and Mark's suggested alternative would not be. I'd also be OK with a rephrasing that didn't use the word consensus to avoid confusion with our usual definition, if it means what @fantasai has been arguing above and what I've been trying to say here.

**Comment by dwsinger** [comment]
Indeed, while we strive for consensus, we also need to make decisions and progress; and we can't give to everyone the power to stop anything (by withholding consensus), without risking paralysis.

**Comment by cwilso** [comment]
Upon reflection:  

- "grounded" refers to the document itself being grounded in the shared values of the W3C community; I think it's appropriate usage.
- I do not think "most" is redundant, because the definition of "consensus" is... unpredictable.  It can be read as as unanimity - which is NOT going to be true - or it can be read as general agreement.  (The M-W definition includes both of these.)  I think "most" makes it clear we are talking about general agreement.  (Yes, I know we do define consensus in the Process, as Mark linked to above; I don't think it's harmful or pointless to underscore a common misconception (that consensus = unanimity) by having one extra word here.)
- I do agree the phrasing is odd, but think that's mostly because the word "emergent" is both complex and unnecessary.  I'd propose removing that word.

**Comment by mnot** [comment]
My concern with the use of the term 'consensus' is that it has a defined meaning in the W3C, and using it will imply to many that the document has been through that process -- it is inherently confusing / misleading to people who are not intimately familiar with this document's particular history, *until* it actually goes through the consensus process.

**Comment by cwilso** [comment]
I believe it would be better to simply remove the word consensus here, because if your argument is (as it appears to be) about the process this document will go through not being good enough to represent consensus, then your suggestion has the same flaw.

The goal was to build a document that is grounded in the shared values of the W3C community and would represent it as a whole, such that 1) it has involved anyone who wanted to be involved, and 2) it could go through the Statement process to actually be declared consensus.  The past few months of this exercise has convinced me the latter is a fool's errand - or at least an errand for Sisyphus, so I think it would be better to replace this line with:

The goal of this document is to represent shared values of the W3C community.

**Comment by mnot** [comment]
> The goal of this document is to represent shared values of the W3C community.

That works. 

> The past few months of this exercise has convinced me the latter is a fool's errand - or at least an errand for Sisyphus

I'm not that gloomy about it. I do think the effort needs clarity about goals, and perhaps a more well-defined venue (e.g., a WG).
